dist: trusty
sudo: required
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - xorg-dev

      # SFML Requires
      - libudev-dev
      - libopenal-dev
      - libflac-dev
      - libvorbis-dev
      - libxrandr-dev

      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev

#before_script:
script:
- mkdir build
- cd build
- cmake --build . --target

# script:
  # - export CC=gcc-7
  # - export CXX=g++-7
  # - cmake --build
